%Script for plotting the tn and alpha values generated by previous script
%CST_ProcessData. 

clear 
close all
clc

loadname='example';
loadname=strcat(loadname,'_tn'); %substructure2

load(loadname)

plotmodes=2*nLebedev; % number of modes to plot, maximally 2*nLebedev.

figure(2)
clf
ax2 = gca;
hold on
grid on 
xlabel('ka')
ylabel('|t_n|')

figure(3)
clf
hold on
ax3 = gca;
grid on
tt2=tt;
newtt=ttproj;

m=1;
plotmodesog=plotmodes;
while m <= plotmodes
    if m > 2*nLebedev      
        disp('No more data')
        disp(strcat('Modes Plotted:',num2str(-1+plotmodesog-(plotmodes-m))))        
        plotmodes=1;
    else
        if max(abs(tt(m,:)))>0.05
            
            figure(2)
            ax2.ColorOrderIndex = m;
            plot(ka,(abs(tt(m,:))))
            
            figure(3)
            ax3.ColorOrderIndex = m;
            newtt(m,abs(newtt(m,:))<0.0005)=nan;
            plot(ka,wrapTo2Pi(angle(newtt(m,1:end))))
        else
            plotmodes=plotmodes+1;
        end
    end
    m=m+1;
end
set(ax3,'YTick',0:pi/2:2*pi)
set(ax3,'YTickLabel',{'0','\pi/2','\pi','3\pi/2','2\pi'})
xlabel('ka')
ylabel('\alpha_n')

